# Generated by Django 5.1.4 on 2025-01-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('html_content', models.TextField(verbose_name='HTML-контент')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/', verbose_name='График')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('salary_from', models.FloatField(blank=True, null=True, verbose_name='Минимальная зарплата')),
                ('salary_to', models.FloatField(blank=True, null=True, verbose_name='Максимальная зарплата')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('key_skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
